# Site settings
author: adeeba reaz
title: why i chose to study software engineering?
header-img: img/home-bg.png
email: adeebarivera@outlook.com
copyright_name: adeeba reaz
description: > # this means to ignore newlines until "baseurl:"
  once upon a time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  adeebarivera

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
